baseurl = "https://jkawamoto.github.io/gii/"
languageCode = "en-us"
title = "gii"
theme = "github-project-landing-page"

[params]
  SubTitle = "Reduce Go import paths"
  Description = """\
    gii lists up repositories which aren't Go projects from your $GOPATH/src\
    and writes them to .goimportsignore so that goimports can ignore those\
    repositories.\
  """
  AuthorName = "Junpei Kawamoto"
  AuthorURL = "https://www.jkawamoto.info/"
  GithubURL = "https://github.com/jkawamoto/gii"
  ProfilePicture = "img/icon.png"

  GithubRepo = "gii"
  GithubOrg = "jkawamoto"

  googleAnalytics = "UA-82315630-1"

  first_color="#f8f8f8"
  first_border_color="#e7e7e7"
  first_text_color="#333"

  second_color="white"
  second_text_color="#333"

  header_color="#f8f8f8"
  header_text_color="rgb(51, 51, 51)"

  header_link_color="#777"
  header_link_hover_color="rgb(51, 51, 51)"
